engines:
  rubocop:
    channel: rubocop-0-50
    enabled: true
    config:
      file: .rubocop.yml
exclude_paths:
  - .rubocop.yml
  - .codeclimate.yml
  - .travis.yml
  - .gitignore
  - .rspec
ratings:
  paths:
  - "spec/tests/**.rb"
  - "lib/**.rb"
