files:
  include:
  - source/_assets/css/**/*.scss
  - source/_assets/css/*.scss
rules:
  indentation: [1, size: 2]
  quotes: [1, style: double]
  no-qualifying-elements: [0]
  class-name-format: [1, convention: hyphenatedbem]
  nesting-depth: [1, max-depth: 4]
  force-element-nesting: [0]
  property-sort-order: [0]
  no-css-comments: [0]
