script: script/test
before_script: script/build
install: script/install
services: [docker]
sudo: required
os: linux
cache:
  bundler: true
  directories:
  - vendor/bundle
deploy:
- provider: script
  script: script/deploy
  on:
    branch: master
