script: script/test
before_script: script/build
install: script/install
services: [docker]
sudo: required
os: linux
addons:
  ssh_known_hosts:
  - envygeeks.io
cache:
  bundler: true
  directories:
  - vendor/bundle
  - node_moduels
deploy:
- skip_cleanup: true
  script: script/deploy
  provider: script
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: change
