script: script/test
before_script: script/build
install: script/install
services: docker
sudo: required
os: linux
addons:
  ssh_known_hosts:
    - envygeeks.io
cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_moduels
deploy:
  - skip_cleanup: true
    script: script/deploy
    provider: script
    on:
      branch: master
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
  - JEKYLL_ENV=production
  - secure: "\
      LmlPyqO+M080pR6Ci13CBPD8iggd5bYj36OGD6hqzzUBcB9LMRUboyayqmWM/18yBV5THM6di\
      AkltzyjhWnNHfNndCaCW8o/N9zHmUGZm87rR4E9J61HuESPXlMojlL75qom1wLMXhtxot/t8x\
      ICztOmjYjFBWXimiCkw34SpzE7jwzqo/tf4glVYaVjClPSjknRjoqNj/LjmMxYCfYFzfMI2qB\
      wgvFZc2gBVSbdrV+SIHIm8AQjYT3jhX1Xea2IuQmgf0nioPTJ9FFAWM1TwX4LPazNmuyEmUSb\
      ym3TAxVUFVCl3pnN2i+xqq91h6D9Gect9RWj8nt0znR4bOZG71t5/MMaAZyF5HzgGdYLPfPs0\
      8L5QFa0EpS8fB56Z+H1PyE/vaew/1N1WGlWba0t85Jww1iOezI5clJdZL1mIyep/k+Zqgp2pI\
      2Dt+Z11645WHb9qU1cC8usOfg1U/gbe83hMhDjU5z7I9z+BFByjzs0qY6+a0gqQWGkQzm/Tpg\
      znk47GiJg/X1m/mbYpBlagukztN3qAkvrjJYJuGyhsHNAX1W23/npUhLuWReysjqZTi5xqp04\
      i4hGkZVsP92uPqnefSgx7UWRzmxhFjtVsMonoTUbPZqrCF2Q/j/Tv0+wKbVyOMfNg5J6jgscw\
      khNoxEnMUQylvl46v1hVisHwfA=\
    "
  - secure: "\
      Rqam4rfL88E2jxnCr8GvXmZ/GUTC2JzkWBksKa3FFQhBzO6tocVXXx1DLR7nFi9GpPBHMsNhm\
      hqyuS/OqWFXPslCfJ60WcZMPrOhUofk8VAz4fnJV2MBeiKFEycFx5J4dF7//GtvOFuio5ROw/\
      TSfV09TUukexdxckHZKPPu0EdiOkRJ4JUYoTaVwnihbFmD00InlTLlLvO19Ruwg6CFf1C/PkV\
      ii9D8ERoW3Z/PRZeilAp7zPNJ13Dae4J3pkQc8JF5g0XMKndD8bJ2ahjPlqSapVo3gLHf4JjZ\
      3YFOx6mSreUuHvSOkfHKeooRn2MxIpsi6sizv509AsU1yqK7mMVV3kJuwObN2rKH5Ipe5vCjh\
      n4t94l+5TTGchTCIEyRVch3oqC10mFPId9tj8qSVGC3VXUdB5aDFMjELDI+a0EPRFdg6TzqJI\
      jpoJBwe4M9r8UZ0i3D2pUGihH2pyp9CNL6gfbAUmCGRjoIY2FuQECW+IqaUd0p48rLpxyTKFW\
      X+EY1x47ztYL0Hkyj12wfIhMV0kOS2msMT99ZCDpvOYjZQ8zxXqarGwyNNLttqF+LoZn0DBrm\
      ef1LQdcGmPb+i/IZYDLeX4eBlquVOCwFFUO0RRsMEB7xEKj/0GF7KgVqlZha+tuX7VkAkAcFe\
      OrjXnY+rQ/mnJCOBXd/352aF3k=\
    "
  - secure: "\
      d1M7TrU0PgEKgxdqnP525ChpdRFExWlATYl9hL6KcB605GqA3fUTLZvmjWV9EInWGRFa2yYuK\
      e7JdwOEcxlMOdrrUWBNzyuA76MtRbBJziwSOOWgZvZcfDiyTCDEXpa5jZM7iOH1DASyMjWI1C\
      7zKPuhj71QBJx0fc+W6kzgz+V01pcl38SCqF37lScrwePp5/hLyfzmeu4XTRUmZiidfpGD62z\
      3qA12/dO2IxrxY//BvwVquSberBpumZKTwsw2qoGe1G4t9e8txQMNn/t8xT5Wcvn35YVNCWnB\
      J0VPFfLWPvKvTZwUF2HtolaBZgFyQSRnQIzKRpuhy2iBvdfoQZK3GB3usZogjI7zLzfY92imf\
      AFgVOPRldvYocIQMzjjnwEJ+JbEybeUGfEl0nCg/bFo2K8wB3+toG7ZVY72evMP7lpa9am5A3\
      77Povgru5iPDHStKr7ulQ92DpFqGV0P4bXGhH6mR3tJSCV2qNwSS9eKfggnQdG9lmAaW2uEoh\
      Na1wFWs7TVY4KIHdImjG+b5tyWERCbbRLf9BTm5VUooWfIVvZpnBLPlCMM6vrrZ8ZwSh90/qf\
      GhM1JH0EOSk6f1COzqgdDRxKYYiFpMCTsk+ZWE8TcEy2HVUTmMN815iJdE71mVutG3kuLo6sF\
      PW2qFYqEUFqQIhortZ7WigZhPw=\
    "
