# --
# _plugins/envygeeks/*
# This is used in my plugins, design and otherwise most
#   likely it will not be shared anywhere.
# --
envygeeks:
  gqlQueryLimit: 12
  hidePageTitles: true
  twitterSite: "@envygeeks"
  twitterCreator: "@envygeeks"
  subTitle: Systems and Programming
  description: The website of Jordon Bedwell; Linux Sysadmin, and Programmer
  enableMinificationInDevelopment: false
  subTitle: Systems and Programming
  githubUsername: envygeeks
  repoName: envygeeks.io
  title: Jordon Bedwell
  ga: UA-18997298-1
  forceSSL: false
  ssl: true
  # --
  # _plugins/envygeeks/drops/archive.rb
  # You can use the following to access it.
  # {{ envygeeks.drops.archives }}
  # --
  archive:
    shuffle: 6
    weights:
      max: 3
      int: 1
  # --
  # _plugins/envygeeks/drops/social.rb
  # You can use the following to access it.
  # {{ envygeeks.drops.social }}
  # --
  socialMedia:
    github: https://github.com/envygeeks
    twitter: https://twitter.com/envygeeks
    mail: mailto:jordon@envygeeks.io
# --
# Jekyll configuration.
# This configuration is unique to Jekyll and only to
#   Jekyll or plugins that wish to share data.
# --
source: ./source
host: envygeeks.io
tz: America/Chicago
plugins_dir: ./plugins
cache_dir: "./.cache"
excerpt_separator: "<!-- MORE -->"
timezone: America/Chicago
destination: ./site
markdown: kramdown
# --
# @see https://github.com/jekyll/jekyll-assets
# @issues https://github.com/jekyll/jekyll-assets
# Jekyll-Assets Configuration
# --
assets:
  features:
    integrity: false
# --
# @see https://github.com/gettalong/kramdown
# @issues https://github.com/gettalong/kramdown
# Kramdown Configuration
# --
kramdown:
  auto_ids: true
# --
# Jekyll
# --
exclude:
- vendor/
- Gemfile
- Readme.md
- .gitignore
- docker-compose.yml
- Gemfile.lock
- Rakefile
- .bundle/
- .git
# --
# jekyll
# --
defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: default
    type: page
- scope:
    type: posts
    path: ""
  values:
    layout: default
    type: post
