source: ./source
tz: America/Chicago
hostname: envygeeks.io
sub_title: Systems and Programming
timezone: America/Chicago
title: Jordon Bedwell
destination: ./site
markdown: kramdown
# --
# jekyll-assets
# --
assets:
  features:
    integrity: true
# --
# kramdown
# --
kramdown:
  auto_ids: true
  syntax_highlighter_opts:
    disable: true
# --
# _plugins/archive
# --
archive:
  shuffle: 6
  weights:
    max: 3
    int: 1
# --
# editing
# --
repo:
  github: envygeeks/envygeeks.io
  web: https://github.com/envygeeks/envygeeks.io
  git: git@github.com:envygeeks/envygeeks.io
  allow_pulls: true
# --
# _plugins/social
# --
social:
  github:  https://github.com/envygeeks
  twitter: https://twitter.com/envygeeks
  email: mailto:jordon@envygeeks.io
# --
# jekyll
# --
exclude:
- vendor/
- Gemfile
- Readme.md
- .gitignore
- docker-compose.yml
- Gemfile.lock
- Rakefile
- .bundle/
- .git
# --
# jekyll
# --
defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: default
    type: page
- scope:
    type: posts
    path: ""
  values:
    layout: default
    type: post
    author:
      handle: envygeeks
      name: Jordon Bedwell
# --
# development
# --
dev:
  domain: localhost
  port: 4000
