source: ./source
host: envygeeks.io
tz: America/Chicago
plugins_dir: ./plugins
cache_dir: "./.jekyll-cache"
excerpt_separator: "<!-- MORE -->"
timezone: America/Chicago
gql_query_limit: 12
destination: ./site
markdown: kramdown
kramdown:
  auto_ids: true
defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: default
    type: page
- scope:
    type: posts
    path: ""
  values:
    layout: default
    type: post
assets:
  source_maps: false
  compression: false
