source: ./source
tz: America/Chicago
hostname: envygeeks.io
sub_title: Systems and Programming
timezone: America/Chicago
title: Jordon Bedwell
destination: ./site
markdown: kramdown
assets:
  features:
    integrity: true
kramdown:
  auto_ids: true
  syntax_highlighter_opts:
    disable: true
archive:
  shuffle: 6
  weights:
    max: 3.0
    int: 2.0
repo:
  github: envygeeks/envygeeks.io
  web: https://github.com/envygeeks/envygeeks.io
  git: git@github.com:envygeeks/envygeeks.io
  allow_pulls: true
social:
  github:  https://github.com/envygeeks
  twitter: https://twitter.com/envygeeks
  email: mailto:jordon@envygeeks.io
exclude:
- nginx/
- vendor/
- _idea/
- Gemfile
- Readme.md
- Dockerfile
- Gemfile.lock
- post-receive
- compose.yml
- nginx.conf
- Rakefile

- .gitignore
- .asset-cache/
- .jekyll-metadata/
- .gitattributes
- .sass-cache/
- .bundle/
- .git
defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: default
    type: page
- scope:
    type: posts
    path: ""
  values:
    layout: default
    type: post
    author:
      handle: envygeeks
      name: Jordon Bedwell
dev:
  domain: localhost
  port: 4000
