gql_query_limit: 12
hide_page_titles: true
twitter_site: "@envygeeks"
twitter_creator: "@envygeeks"
sub_title: Systems and Programming
description: The website of Jordon Bedwell; Linux Sysadmin, and Programmer
sub_title: Systems and Programming
title: Jordon Bedwell
ga: UA-18997298-1
force_ssl: false
ssl: true
# --
# _plugins/envygeeks/drops/social.rb
# You can use the following to access it.
# {{ envygeeks.drops.social }}
# --
social:
  github: https://github.com/envygeeks
  twitter: https://twitter.com/envygeeks
  mail: mailto:jordon@envygeeks.io
# --
# Jekyll configuration.
# This configuration is unique to Jekyll and only to
#   Jekyll or plugins that wish to share data.
# --
source: ./source
host: envygeeks.io
tz: America/Chicago
plugins_dir: ./plugins
cache_dir: "./.jekyll-cache"
excerpt_separator: "<!-- MORE -->"
timezone: America/Chicago
destination: ./site
markdown: kramdown
# --
# @see https://github.com/gettalong/kramdown
# @issues https://github.com/gettalong/kramdown
# Kramdown Configuration
# --
kramdown:
  auto_ids: true
# --
# Jekyll
# --
defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: default
    type: page
- scope:
    type: posts
    path: ""
  values:
    layout: default
    type: post
