source: ./source
host: envygeeks.io
tz: America/Chicago
hide-page-titles: true
plugins_dir: ./plugins
excerpt_separator: "<!-- MORE -->"
sub-title: Systems and Programming
timezone: America/Chicago
title: Jordon Bedwell
destination: ./site
markdown: kramdown
ga: UA-18997298-1
force_ssl: false
ssl: true
# --
# jekyll-assets
# --
assets:
  features:
    integrity: false
# --
# kramdown
# --
kramdown:
  auto_ids: true
  syntax_highlighter_opts:
    disable: true
# --
# _plugins/archive
# --
archive:
  shuffle: 6
  weights:
    max: 3
    int: 1
# --
# editing
# --
site-repo:
  github: envygeeks/envygeeks.io
  gitweb: https://github.com/envygeeks/envygeeks.io
  giturl: git@github.com:envygeeks/envygeeks.io
  allow-pulls: true
# --
# _plugins/social
# --
social-media:
  github:  https://github.com/envygeeks
  twitter: https://twitter.com/envygeeks
  envelope: mailto:jordon@envygeeks.io
# --
# Jekyll
# --
exclude:
- vendor/
- Gemfile
- Readme.md
- .gitignore
- docker-compose.yml
- Gemfile.lock
- Rakefile
- .bundle/
- .git
# --
# jekyll
# --
defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: default
    type: page
- scope:
    type: posts
    path: ""
  values:
    layout: default
    type: post
    author:
      handle: envygeeks
      name: Jordon Bedwell
